# This is for units that don't match specific categories.
states = [
    { initweight = 1.0, finalweight = 0.5 },
    { initweight = 0.0, finalweight = 0.5 },
]

arcs = [
    { src = 1, dest = 2, weight = 0.5 },
    { src = 2, dest = 2, weight = 0.5 },
]

# For all nonspeech-units
[nonspeech-unit]
states = [
    { initweight = 1.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.4 },
]

arcs = [
    { src = 1, dest = 1, weight = 0.9 },
    { src = 1, dest = 2, weight = 0.05 },
    { src = 1, dest = 3, weight = 0.025 },
    { src = 1, dest = 4, weight = 0.025 },
    { src = 2, dest = 2, weight = 0.9 },
    { src = 2, dest = 3, weight = 0.05 },
    { src = 2, dest = 4, weight = 0.025 },
    { src = 2, dest = 5, weight = 0.025 },
    { src = 3, dest = 3, weight = 0.9 },
    { src = 3, dest = 2, weight = 0.05 },
    { src = 3, dest = 4, weight = 0.025 },
    { src = 3, dest = 5, weight = 0.025 },
    { src = 4, dest = 4, weight = 0.9 },
    { src = 4, dest = 2, weight = 0.05 },
    { src = 4, dest = 3, weight = 0.025 },
    { src = 4, dest = 5, weight = 0.025 },
    { src = 5, dest = 5, weight = 0.6 },
]

# For phones
[speech-unit.phone]
states = [
    { initweight = 1.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.25 },
    { initweight = 0.0, finalweight = 0.4 },
]

arcs = [
    { src = 1, dest = 1, weight = 0.6 },
    { src = 1, dest = 2, weight = 0.4 },
    { src = 2, dest = 2, weight = 0.5 },
    { src = 2, dest = 3, weight = 0.25 },
    { src = 3, dest = 3, weight = 0.6 },
]

# For spoken-noise
[speech-unit.spoken-noise]
states = [
    { initweight = 1.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.0 },
    { initweight = 0.0, finalweight = 0.25 },
]

arcs = [
    { src = 1, dest = 1, weight = 0.25 },
    { src = 1, dest = 2, weight = 0.25 },
    { src = 1, dest = 3, weight = 0.25 },
    { src = 1, dest = 4, weight = 0.25 },
    { src = 2, dest = 2, weight = 0.25 },
    { src = 2, dest = 1, weight = 0.25 },
    { src = 2, dest = 3, weight = 0.25 },
    { src = 2, dest = 4, weight = 0.25 },
    { src = 3, dest = 3, weight = 0.25 },
    { src = 3, dest = 1, weight = 0.25 },
    { src = 3, dest = 2, weight = 0.25 },
    { src = 3, dest = 4, weight = 0.25 },
    { src = 4, dest = 4, weight = 0.25 },
    { src = 4, dest = 2, weight = 0.25 },
    { src = 4, dest = 3, weight = 0.25 },
    { src = 4, dest = 5, weight = 0.25 },
    { src = 5, dest = 5, weight = 0.75 },
]

